blank_issues_enabled: true
contact_links:
  - name: Disord
    url: https://discord.com/channels/594997912983830566/1087353381284225064
    about: Go to (#forum for Q&A, Feature Requests, Vehicle Requests, Map Requests, and Balancing)
